### ISSUE TITLE
Include in Gradle Plugin Portal

### ISSUE THREAD

**Issue by ethauvin** [coders-kitchen/CompileOnlyPlugin#1]
Please include in the [Gradle Plugin Portal](https://plugins.gradle.org/docs/publish-plugin). that will make it a lot easier to use.

I can submit a PR with the proper modifications to the build file if that will help, although you'll have to get your own API key.

Thanks!

**Comment by coders-kitchen** [comment]
Hi!

Thanks for this idea, it would be great if you could provide the necessary changes via a PR.

Thanks in advance

Peter

**Comment by ethauvin** [comment]
No problem. I'll work on it over the weekend.

**Comment by ethauvin** [comment]
I guess it wasn't in the cards for this weekend. I have to have surgery today or tomorrow and will work on it as soon as I'm back on my feet.

**Comment by coders-kitchen** [comment]
Oh I see. Get well soon and take your time to recover.

**Comment by ethauvin** [comment]
See #2
